import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, JetBrains_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/components/QueryProvider"
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "OUTBREAK",
  description: "Generated by create next app",
};
const inter = Outfit({ subsets: ["latin"], weight: ["400"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen ${inter.className}`}
      >
        <QueryProvider>
          <Toaster />
        {children}
        </QueryProvider>
      </body>
    </html>
  );
}
